# Generated by Django 4.2.3 on 2023-07-25 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('activation_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(choices=[('G', 'Grand Parent'), ('P', 'Parent'), ('C', 'Child')], default='P', max_length=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('got_from', models.CharField(max_length=30)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ordered_from', models.CharField(max_length=30)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
    ]
