# Generated by Django 4.2.3 on 2023-07-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_member_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['last_update']},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profit',
            options={'ordering': ['last_update']},
        ),
    ]
