# Generated by Django 4.2.3 on 2023-07-26 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_family_options_alter_member_options_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='family',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='family',
        #     name='activation_code',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False),
        # ),
    ]
