# Generated by Django 4.2.3 on 2023-07-26 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_family_id_alter_family_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
