# Generated by Django 4.2.3 on 2023-07-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_family_activation_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profit',
            new_name='Revenue',
        ),
    ]
