# Generated by Django 4.2.3 on 2023-07-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_profit_revenue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revenue',
            new_name='Earning',
        ),
    ]
