# Generated by Django 4.2.3 on 2023-07-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_revenue_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='monetary_value',
        ),
    ]
