# Generated by Django 4.2.3 on 2023-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_value_expense_monetary_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='value',
            new_name='monetary_value',
        ),
    ]
