# Generated by Django 4.2.3 on 2023-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_rename_value_earning_monetary_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='tracker.member'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='tracker.member'),
        ),
    ]
