# Generated by Django 4.2.3 on 2023-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_earning_member_alter_expense_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
