# Generated by Django 4.2.3 on 2023-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_expense_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='last_update',
            field=models.DateField(),
        ),
    ]
