# Generated by Django 4.2.3 on 2023-07-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_earning_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='got_from',
            new_name='received_from',
        ),
    ]
