# Generated by Django 4.2.3 on 2023-07-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_rename_got_from_earning_received_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earning',
            options={'ordering': ['received_from']},
        ),
        migrations.RenameField(
            model_name='earning',
            old_name='last_update',
            new_name='received_date',
        ),
    ]
