# Generated by Django 4.2.3 on 2023-07-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_earning_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['paid_date']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='last_update',
            new_name='paid_date',
        ),
    ]
