# Generated by Django 4.2.3 on 2023-07-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='ordered_from',
            new_name='paid_to',
        ),
    ]
