# Generated by Django 4.2.3 on 2023-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_rename_ordered_from_expense_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='received_from',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='earning',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
