# Generated by Django 4.2.3 on 2023-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_alter_earning_monetary_value_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='family',
        #     name='date_created',
        #     field=models.DateTimeField(default=1),
        #     preserve_default=False,
        # ),
    ]
