# Generated by Django 4.2.3 on 2023-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_family_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='date_created',
            field=models.DateTimeField(default='2023-07-01'),
            preserve_default=False,
        ),
    ]
