# Generated by Django 4.2.3 on 2023-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_family_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='password',
            field=models.CharField(default='zcc20040220', max_length=20),
            preserve_default=False,
        ),
    ]
