# Generated by Django 4.2.3 on 2023-07-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_alter_family_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='activation_code',
            new_name='id',
        ),
    ]
