# Generated by Django 4.2.3 on 2023-08-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_alter_member_family'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='earning',
        #     name='member',
        # ),
        # migrations.RemoveField(
        #     model_name='expense',
        #     name='member',
        # ),
        # migrations.AddField(
        #     model_name='member',
        #     name='earning',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to='tracker.earning'),
        # ),
        # migrations.AddField(
        #     model_name='member',
        #     name='expense',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to='tracker.expense'),
        # ),
    ]
