# Generated by Django 4.2.3 on 2023-08-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_remove_earning_member_remove_expense_member_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='member',
        #     name='earning',
        # ),
        # migrations.RemoveField(
        #     model_name='member',
        #     name='expense',
        # ),
        # migrations.AddField(
        #     model_name='earning',
        #     name='member',
        #     field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='tracker.member'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='member',
        #     field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='tracker.member'),
        #     preserve_default=False,
        # ),
    ]
