# Generated by Django 4.2.3 on 2023-08-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_remove_member_earning_remove_member_expense_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='earning',
        #     name='member',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earning', to='tracker.member'),
        # ),
        # migrations.AlterField(
        #     model_name='expense',
        #     name='member',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='tracker.member'),
        # ),
    ]
