# Generated by Django 4.2.3 on 2023-08-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_alter_earning_member_alter_expense_member'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='earning',
        #     name='member',
        # ),
        # migrations.RemoveField(
        #     model_name='expense',
        #     name='member',
        # ),
    ]
