# Generated by Django 4.2.3 on 2023-08-11 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0055_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
