# Generated by Django 4.2.4 on 2023-08-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0056_alter_family_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tracker/images')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.member')),
            ],
        ),
    ]
