# Generated by Django 4.2.4 on 2023-08-24 17:35

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0057_memberimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimage',
            name='image',
            field=models.ImageField(upload_to='tracker/images', validators=[tracker.validators.validate_file_size]),
        ),
    ]
