# Generated by Django 4.2.4 on 2023-08-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0058_alter_memberimage_image'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='earning',
        #     name='title',
        #     field=models.CharField(max_length=20),
        # ),
        # migrations.AlterField(
        #     model_name='expense',
        #     name='title',
        #     field=models.CharField(max_length=20),
        # ),
    ]
