# Generated by Django 4.2.4 on 2023-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0062_alter_earning_title_alter_expense_title'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='earning',
        #     name='title',
        #     field=models.CharField(max_length=20),
        # ),
        # migrations.AlterField(
        #     model_name='expense',
        #     name='title',
        #     field=models.CharField(max_length=20),
        # ),
    ]
